language: node_js
sudo: false
script: npm run ${NPM_SCRIPT}
after_success: cat ${TRAVIS_BUILD_DIR}/coverage/lcov.info | coveralls
node_js:
  - '6'
  - '8'
env:
  global:
  # SAUCE_USERNAME
  - secure: Z21+fRlqB/e47iLnKKyfp1J2R9aXbytXbToOQ6k6/7UJWp0Zg1VnYJ/m8g+uoTj1s7WqBx6hdly9bPVtiQ6/WWUIek50Q6xrx0j1X3aWWeLDCyCFE3nwBeLu0YNXQehF8TPfdWoxLNy9g4Y2tX0RPQCZ8aeV639d+6Hc4Etjp+E=
  # SAUCE_ACCESS_KEY
  - secure: L0m7LKhlXK3hob+0jwVCAE7qGd9x+9shMN8OthTTV7lHyz83Ypv3FMEKQtDYho9d24i1SidJbtvpFrkKBLGkn94JzrNE/8UcKPNiIWLHc2bvQ15/aS2XH7nrloWLI8hoavs0A3dJUCFyPY8auRop4Z/vOnFZuDBGuziyZFuZeds=

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true
  include:
    - env: NPM_SCRIPT=lint

    # unit tests
    - env: NPM_SCRIPT='test-unit --coverage'

    # functional tests that do not require browsers
    - env: NPM_SCRIPT='test-func --coverage'

    # functional tests that require browsers
    - env:
      - BROWSER=chrome
      - NPM_SCRIPT='test-browser --coverage'
    - env:
      - BROWSER=firefox
      - NPM_SCRIPT='test-browser --coverage'
    - env:
      - BROWSER=ie8
      - NPM_SCRIPT='test-browser --coverage'
    - env:
      - BROWSER=ie9
      - NPM_SCRIPT='test-browser --coverage'
    - env:
      - BROWSER=ie10
      - NPM_SCRIPT='test-browser --coverage'
    - env:
      - BROWSER=ie11
      - NPM_SCRIPT='test-browser --coverage'
    - env:
      - BROWSER=opera12
      - NPM_SCRIPT='test-browser --coverage'
    - env:
      - BROWSER=android4.4
      - NPM_SCRIPT='test-browser --coverage'
    - env:
      - BROWSER=android5
      - NPM_SCRIPT='test-browser --coverage'
